// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Id struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{0}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type IdInt struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdInt) Reset()         { *m = IdInt{} }
func (m *IdInt) String() string { return proto.CompactTextString(m) }
func (*IdInt) ProtoMessage()    {}
func (*IdInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{1}
}

func (m *IdInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdInt.Unmarshal(m, b)
}
func (m *IdInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdInt.Marshal(b, m, deterministic)
}
func (m *IdInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdInt.Merge(m, src)
}
func (m *IdInt) XXX_Size() int {
	return xxx_messageInfo_IdInt.Size(m)
}
func (m *IdInt) XXX_DiscardUnknown() {
	xxx_messageInfo_IdInt.DiscardUnknown(m)
}

var xxx_messageInfo_IdInt proto.InternalMessageInfo

func (m *IdInt) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Ids struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{2}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Info struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{4}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Info) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Info) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Pager struct {
	Paged                int32    `protobuf:"varint,1,opt,name=paged,proto3" json:"paged,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pager) Reset()         { *m = Pager{} }
func (m *Pager) String() string { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()    {}
func (*Pager) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{6}
}

func (m *Pager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pager.Unmarshal(m, b)
}
func (m *Pager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pager.Marshal(b, m, deterministic)
}
func (m *Pager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pager.Merge(m, src)
}
func (m *Pager) XXX_Size() int {
	return xxx_messageInfo_Pager.Size(m)
}
func (m *Pager) XXX_DiscardUnknown() {
	xxx_messageInfo_Pager.DiscardUnknown(m)
}

var xxx_messageInfo_Pager proto.InternalMessageInfo

func (m *Pager) GetPaged() int32 {
	if m != nil {
		return m.Paged
	}
	return 0
}

func (m *Pager) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Pager) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type BaseWhere struct {
	Paged    int32 `protobuf:"varint,1,opt,name=paged,proto3" json:"paged,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Top      int32 `protobuf:"varint,3,opt,name=top,proto3" json:"top,omitempty"`
	//base params
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Ids                  int64    `protobuf:"varint,5,opt,name=ids,proto3" json:"ids,omitempty"`
	Keywords             string   `protobuf:"bytes,6,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	AreaId               int64    `protobuf:"varint,8,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	TypeId               int32    `protobuf:"varint,9,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	CatId                int32    `protobuf:"varint,10,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	StartDate            string   `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,12,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseWhere) Reset()         { *m = BaseWhere{} }
func (m *BaseWhere) String() string { return proto.CompactTextString(m) }
func (*BaseWhere) ProtoMessage()    {}
func (*BaseWhere) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{7}
}

func (m *BaseWhere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseWhere.Unmarshal(m, b)
}
func (m *BaseWhere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseWhere.Marshal(b, m, deterministic)
}
func (m *BaseWhere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseWhere.Merge(m, src)
}
func (m *BaseWhere) XXX_Size() int {
	return xxx_messageInfo_BaseWhere.Size(m)
}
func (m *BaseWhere) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseWhere.DiscardUnknown(m)
}

var xxx_messageInfo_BaseWhere proto.InternalMessageInfo

func (m *BaseWhere) GetPaged() int32 {
	if m != nil {
		return m.Paged
	}
	return 0
}

func (m *BaseWhere) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *BaseWhere) GetTop() int32 {
	if m != nil {
		return m.Top
	}
	return 0
}

func (m *BaseWhere) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BaseWhere) GetIds() int64 {
	if m != nil {
		return m.Ids
	}
	return 0
}

func (m *BaseWhere) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *BaseWhere) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BaseWhere) GetAreaId() int64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *BaseWhere) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *BaseWhere) GetCatId() int32 {
	if m != nil {
		return m.CatId
	}
	return 0
}

func (m *BaseWhere) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *BaseWhere) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

//令牌
type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e36566fe4e50c15, []int{8}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Id)(nil), "Id")
	proto.RegisterType((*IdInt)(nil), "IdInt")
	proto.RegisterType((*Ids)(nil), "Ids")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Pager)(nil), "Pager")
	proto.RegisterType((*BaseWhere)(nil), "BaseWhere")
	proto.RegisterType((*Token)(nil), "Token")
}

func init() { proto.RegisterFile("protobuf/common.proto", fileDescriptor_2e36566fe4e50c15) }

var fileDescriptor_2e36566fe4e50c15 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xb5, 0xc9, 0x3a, 0x9b, 0xcc, 0x56, 0xa8, 0xb2, 0xb6, 0x34, 0xfc, 0x93, 0x4a, 0x4e,
	0x3d, 0x15, 0x09, 0xc4, 0x0b, 0x20, 0x7a, 0xc8, 0x6d, 0x15, 0x90, 0xb8, 0x11, 0x79, 0xe3, 0xe9,
	0x12, 0xb5, 0xb1, 0x23, 0x7b, 0x16, 0xb4, 0xfb, 0x46, 0xbc, 0x25, 0xf2, 0x38, 0x41, 0x7b, 0xee,
	0x6d, 0x7e, 0xdf, 0x17, 0x8f, 0x3d, 0x5f, 0x06, 0xae, 0x46, 0x67, 0xc9, 0xee, 0x0e, 0x0f, 0x1f,
	0x3a, 0x3b, 0x0c, 0xd6, 0xdc, 0x31, 0x57, 0x1b, 0x48, 0x6a, 0x2d, 0x5f, 0x40, 0xd2, 0xeb, 0x72,
	0x71, 0xb3, 0xb8, 0x4d, 0x9b, 0xa4, 0xd7, 0xd5, 0x35, 0x88, 0x5a, 0xd7, 0x86, 0xce, 0x0c, 0x31,
	0x19, 0x69, 0xad, 0xbd, 0xbc, 0x84, 0xb4, 0xd7, 0xbe, 0x5c, 0xdc, 0xa4, 0xb7, 0x69, 0x13, 0xca,
	0x6a, 0x05, 0xe2, 0x7e, 0x18, 0xe9, 0x58, 0x6d, 0x61, 0x59, 0x9b, 0x07, 0x2b, 0x4b, 0x58, 0x75,
	0xd6, 0x10, 0x1a, 0xe2, 0xe3, 0x45, 0x33, 0xa3, 0x7c, 0x09, 0x99, 0x39, 0x0c, 0x3b, 0x74, 0x65,
	0xc2, 0x7d, 0x27, 0x0a, 0xba, 0x27, 0x45, 0x07, 0x5f, 0xa6, 0x7c, 0x60, 0xa2, 0xea, 0x33, 0x88,
	0x7b, 0xe7, 0xac, 0x93, 0x12, 0x96, 0x9d, 0xd5, 0x38, 0x3d, 0x87, 0xeb, 0x70, 0xcd, 0x80, 0xde,
	0xab, 0x3d, 0x72, 0xb7, 0xa2, 0x99, 0xb1, 0xda, 0x82, 0xd8, 0xaa, 0x3d, 0x3a, 0xb9, 0x01, 0x31,
	0xaa, 0x3d, 0xce, 0x63, 0x44, 0x90, 0x6f, 0xa0, 0x08, 0x45, 0xeb, 0xfb, 0x13, 0x4e, 0x0f, 0xc9,
	0x83, 0xf0, 0xad, 0x3f, 0x61, 0x38, 0x42, 0x96, 0xd4, 0x13, 0xbf, 0x44, 0x34, 0x11, 0xaa, 0xbf,
	0x09, 0x14, 0x5f, 0x94, 0xc7, 0x1f, 0xbf, 0xd0, 0xe1, 0x73, 0xda, 0x5e, 0x42, 0x4a, 0x76, 0x9c,
	0x9a, 0x86, 0x72, 0xca, 0x77, 0x39, 0x07, 0x3f, 0x07, 0x2b, 0x58, 0x08, 0xa5, 0x7c, 0x0d, 0xf9,
	0x23, 0x1e, 0xff, 0x58, 0xa7, 0x7d, 0x99, 0xf1, 0x84, 0xff, 0xf9, 0x2c, 0xb1, 0xd5, 0x79, 0x62,
	0xf2, 0x1a, 0x56, 0xca, 0xa1, 0x6a, 0x7b, 0x5d, 0xe6, 0xdc, 0x29, 0x0b, 0x58, 0xeb, 0x60, 0xd0,
	0x71, 0xc4, 0x60, 0x14, 0x31, 0xfb, 0x80, 0xb5, 0x96, 0x57, 0x90, 0x75, 0x8a, 0x82, 0x0e, 0x71,
	0x9a, 0x4e, 0x51, 0xad, 0xe5, 0x3b, 0x00, 0x4f, 0xca, 0x51, 0xab, 0x15, 0x61, 0xb9, 0xe6, 0x4b,
	0x0a, 0x56, 0xbe, 0x2a, 0x42, 0xf9, 0x0a, 0x72, 0x34, 0x3a, 0x9a, 0x17, 0x31, 0x7d, 0x34, 0x3a,
	0x58, 0xd5, 0x4f, 0x10, 0xdf, 0xed, 0x23, 0x1a, 0xf9, 0x1e, 0x2e, 0x54, 0xd7, 0xa1, 0xf7, 0x2d,
	0x05, 0x9e, 0x96, 0x61, 0x1d, 0xb5, 0xf8, 0xc9, 0x06, 0xc4, 0x6f, 0xf5, 0xd4, 0x6b, 0xce, 0x2b,
	0x6f, 0x22, 0xc8, 0xb7, 0x20, 0x30, 0xfc, 0x76, 0x8e, 0x6b, 0xfd, 0x31, 0xbb, 0xe3, 0x25, 0x68,
	0xa2, 0xb8, 0xcb, 0x78, 0x7d, 0x3f, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x2a, 0x36, 0x91,
	0xd7, 0x02, 0x00, 0x00,
}
